version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        image: laravel_app_image
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            # Задайте переменные окружения для Laravel
            APP_ENV: local
            APP_DEBUG: true
            APP_URL: http://localhost
            DB_CONNECTION: mysql
            DB_HOST: localhost
            DB_PORT: 3306
            DB_DATABASE: ''
            DB_USERNAME: ''
            DB_PASSWORD: ''
